[package]
name = "ch34-serde-json"
edition.workspace = true
version.workspace = true

[[bin]]
name = "ch34"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3"
validator = { version = "0.18", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
